-- =====================================================================================
-- Benlle storefront + admin: database schema, security rules, functions and storage.
-- Run the generated setup.sql (this file + seed data) once in: Supabase → SQL Editor.
-- It is safe to re-run.
-- =====================================================================================

-- ---------- Admin identity ----------------------------------------------------------
-- The owner is whoever holds a CONFIRMED Supabase Auth account with the email below.
create table if not exists public.admins (
  user_id uuid primary key references auth.users (id) on delete cascade,
  created_at timestamptz not null default now()
);

create or replace function public.is_admin() returns boolean
language sql stable security definer set search_path = public as $$
  select exists (
    select 1 from public.admins a
    join auth.users u on u.id = a.user_id
    where a.user_id = auth.uid() and u.email_confirmed_at is not null
  );
$$;

create or replace function public.handle_new_user() returns trigger
language plpgsql security definer set search_path = public as $$
begin
  if lower(new.email) = 'betsykitur@gmail.com' then
    insert into public.admins (user_id) values (new.id) on conflict do nothing;
  end if;
  return new;
end;
$$;
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute function public.handle_new_user();
-- If the owner account already exists, claim it now.
insert into public.admins (user_id) select id from auth.users where lower(email) = 'betsykitur@gmail.com' on conflict do nothing;

alter table public.admins enable row level security;
drop policy if exists "admins read own" on public.admins;
create policy "admins read own" on public.admins for select using (user_id = auth.uid());

-- ---------- Catalogue ---------------------------------------------------------------
create table if not exists public.categories (
  id text primary key,
  label text not null check (char_length(label) between 1 and 80),
  position int not null default 0
);

create table if not exists public.products (
  id text primary key,
  position bigint generated by default as identity,
  slug text not null unique,
  name text not null check (char_length(name) between 1 and 160),
  subtitle text not null default '',
  category text not null default '',
  price numeric(10,2) not null check (price >= 0),
  badge text not null default '',
  rating numeric(2,1) not null default 0 check (rating between 0 and 5),
  reviews int not null default 0 check (reviews >= 0),
  stock int not null default 0 check (stock >= 0),
  image text not null default '',
  gallery jsonb not null default '[]'::jsonb,
  status text not null default 'active' check (status in ('active', 'draft')),
  featured boolean not null default false,
  description text not null default '',
  ingredients jsonb not null default '[]'::jsonb,
  size text not null default '',
  created_at timestamptz not null default now()
);
create index if not exists products_category_idx on public.products (category);

-- ---------- Website content (homepage sections, hero, collections, settings …) ----------
-- One JSON document per key. Keys: sections, hero, manifesto, collections, menu, about, routine,
-- trust, testimonials, settings. Image URLs live inside these documents and in products/journal.
create table if not exists public.cms_documents (
  key text primary key,
  value jsonb not null,
  updated_at timestamptz not null default now()
);

create table if not exists public.journal_posts (
  id text primary key,
  slug text not null unique,
  title text not null,
  excerpt text not null default '',
  category text not null default 'Journal',
  image text not null default '',
  date date not null default current_date,
  read_time int not null default 1,
  published boolean not null default true,
  body jsonb not null default '[]'::jsonb
);

-- Every image the site uses or the owner uploads (files live in the "images" storage bucket).
create table if not exists public.media_assets (
  id uuid primary key default gen_random_uuid(),
  url text not null unique,
  path text,
  created_at timestamptz not null default now()
);

-- ---------- Orders & customers ------------------------------------------------------
create table if not exists public.orders (
  id text primary key,
  user_id uuid references auth.users (id) on delete set null default auth.uid(),
  email text not null,
  customer jsonb not null default '{}'::jsonb,
  shipping_address jsonb not null default '{}'::jsonb,
  status text not null default 'pending' check (status in ('pending', 'processing', 'shipped', 'delivered', 'cancelled')),
  items jsonb not null default '[]'::jsonb,
  item_count int not null default 0,
  subtotal numeric(10,2) not null,
  shipping numeric(10,2) not null default 0,
  total numeric(10,2) not null,
  date timestamptz not null default now()
);
create index if not exists orders_user_idx on public.orders (user_id);
create index if not exists orders_email_idx on public.orders (email);

create table if not exists public.addresses (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  label text not null,
  name text not null,
  address text not null,
  city text not null,
  zip text not null,
  country text not null,
  is_default boolean not null default false,
  created_at timestamptz not null default now()
);
create unique index if not exists addresses_one_default on public.addresses (user_id) where is_default;

create table if not exists public.messages (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  email text not null,
  subject text not null default '',
  message text not null,
  read boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.subscribers (
  email text primary key,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

-- ---------- Money: where the owner receives payouts (admin only) ----------------------
-- Store identifiers only (till numbers, account names). Never put API secrets in this table.
create table if not exists public.payout_methods (
  id uuid primary key default gen_random_uuid(),
  type text not null check (type in ('mpesa', 'bank', 'paypal', 'card', 'other')),
  label text not null,
  details jsonb not null default '{}'::jsonb,
  enabled boolean not null default true,
  is_default boolean not null default false,
  created_at timestamptz not null default now()
);
create unique index if not exists payout_one_default on public.payout_methods ((true)) where is_default;

-- ---------- Shopper interest: what visitors added to carts / wishlists -------------------
create table if not exists public.shopper_activity (
  id bigint generated always as identity primary key,
  session_id text not null check (char_length(session_id) <= 64),
  user_id uuid,
  user_email text,
  kind text not null check (kind in ('add_to_cart', 'wishlist_add', 'wishlist_remove')),
  product_id text not null,
  qty int not null default 1 check (qty between 1 and 99),
  created_at timestamptz not null default now()
);
create index if not exists shopper_activity_product_idx on public.shopper_activity (product_id);
create index if not exists shopper_activity_created_idx on public.shopper_activity (created_at desc);

-- The server fills in who the shopper is, so it cannot be spoofed from the browser.
create or replace function public.stamp_activity() returns trigger
language plpgsql security definer set search_path = public as $$
begin
  new.user_id := auth.uid();
  new.user_email := (select email from auth.users where id = auth.uid());
  return new;
end;
$$;
drop trigger if exists stamp_activity on public.shopper_activity;
create trigger stamp_activity before insert on public.shopper_activity for each row execute function public.stamp_activity();

-- ---------- Row-level security ----------------------------------------------------------
alter table public.categories enable row level security;
alter table public.products enable row level security;
alter table public.cms_documents enable row level security;
alter table public.journal_posts enable row level security;
alter table public.media_assets enable row level security;
alter table public.orders enable row level security;
alter table public.addresses enable row level security;
alter table public.messages enable row level security;
alter table public.subscribers enable row level security;
alter table public.payout_methods enable row level security;
alter table public.shopper_activity enable row level security;

do $$
declare t text;
begin
  -- Public read, admin write
  foreach t in array array['categories', 'cms_documents', 'media_assets'] loop
    execute format('drop policy if exists "%1$s public read" on public.%1$s', t);
    execute format('create policy "%1$s public read" on public.%1$s for select using (true)', t);
    execute format('drop policy if exists "%1$s admin write" on public.%1$s', t);
    execute format('create policy "%1$s admin write" on public.%1$s for all using (public.is_admin()) with check (public.is_admin())', t);
  end loop;
  -- Admin only
  foreach t in array array['subscribers', 'payout_methods'] loop
    execute format('drop policy if exists "%1$s admin only" on public.%1$s', t);
    execute format('create policy "%1$s admin only" on public.%1$s for all using (public.is_admin()) with check (public.is_admin())', t);
  end loop;
end $$;

drop policy if exists "products read" on public.products;
create policy "products read" on public.products for select using (status = 'active' or public.is_admin());
drop policy if exists "products admin write" on public.products;
create policy "products admin write" on public.products for all using (public.is_admin()) with check (public.is_admin());

drop policy if exists "journal read" on public.journal_posts;
create policy "journal read" on public.journal_posts for select using (published or public.is_admin());
drop policy if exists "journal admin write" on public.journal_posts;
create policy "journal admin write" on public.journal_posts for all using (public.is_admin()) with check (public.is_admin());

-- Orders are created only through place_order(); customers read their own, the owner reads all.
drop policy if exists "orders read" on public.orders;
create policy "orders read" on public.orders for select using (user_id = auth.uid() or public.is_admin());
drop policy if exists "orders admin update" on public.orders;
create policy "orders admin update" on public.orders for update using (public.is_admin()) with check (public.is_admin());

drop policy if exists "addresses owner" on public.addresses;
create policy "addresses owner" on public.addresses for all using (user_id = auth.uid()) with check (user_id = auth.uid());

drop policy if exists "messages insert" on public.messages;
create policy "messages insert" on public.messages for insert with check (
  read = false and char_length(name) between 1 and 200 and char_length(subject) <= 300
  and char_length(message) between 5 and 5000 and email ~* '^[^@\s]+@[^@\s]+\.[^@\s]+$'
);
drop policy if exists "messages admin" on public.messages;
create policy "messages admin" on public.messages for select using (public.is_admin());
drop policy if exists "messages admin update" on public.messages;
create policy "messages admin update" on public.messages for update using (public.is_admin()) with check (public.is_admin());
drop policy if exists "messages admin delete" on public.messages;
create policy "messages admin delete" on public.messages for delete using (public.is_admin());

drop policy if exists "activity insert" on public.shopper_activity;
create policy "activity insert" on public.shopper_activity for insert with check (true);
drop policy if exists "activity admin read" on public.shopper_activity;
create policy "activity admin read" on public.shopper_activity for select using (public.is_admin());
drop policy if exists "activity admin delete" on public.shopper_activity;
create policy "activity admin delete" on public.shopper_activity for delete using (public.is_admin());

-- ---------- Functions the storefront calls ------------------------------------------------
-- Checkout. Prices, stock and shipping are decided HERE, never trusted from the browser.
create or replace function public.place_order(p_customer jsonb, p_items jsonb) returns jsonb
language plpgsql security definer set search_path = public as $$
declare
  k text; r record; v_prod public.products%rowtype; v_lines jsonb := '[]'::jsonb;
  v_sub numeric := 0; v_count int := 0; v_ship numeric; v_settings jsonb; v_thresh numeric; v_flat numeric;
  v_addr jsonb; v_email text; v_order public.orders%rowtype;
begin
  if p_customer is null or jsonb_typeof(p_customer) <> 'object' then raise exception 'Missing customer details'; end if;
  foreach k in array array['name', 'email', 'address', 'city', 'zip', 'country'] loop
    if coalesce(trim(p_customer ->> k), '') = '' then raise exception 'Please fill in your %', k; end if;
    if char_length(p_customer ->> k) > 300 then raise exception 'Your % is too long', k; end if;
  end loop;
  v_email := lower(trim(p_customer ->> 'email'));
  if v_email !~* '^[^@\s]+@[^@\s]+\.[^@\s]+$' then raise exception 'Enter a valid email address'; end if;
  if p_items is null or jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items) not between 1 and 50 then
    raise exception 'Your bag is empty';
  end if;
  for r in select e from jsonb_array_elements(p_items) e loop
    if coalesce(r.e ->> 'id', '') = '' or coalesce(r.e ->> 'qty', '') !~ '^[0-9]{1,2}$' or (r.e ->> 'qty')::int < 1 then
      raise exception 'Your bag has an invalid item';
    end if;
  end loop;

  for r in select e ->> 'id' as id, sum((e ->> 'qty')::int)::int as qty
           from jsonb_array_elements(p_items) e group by e ->> 'id' order by e ->> 'id' loop
    select * into v_prod from public.products where id = r.id and status = 'active' for update;
    if not found then raise exception 'An item in your bag is no longer available'; end if;
    if v_prod.stock < r.qty then
      raise exception 'Only % left of %', v_prod.stock, v_prod.name;
    end if;
    update public.products set stock = stock - r.qty where id = v_prod.id;
    v_sub := v_sub + v_prod.price * r.qty;
    v_count := v_count + r.qty;
    v_lines := v_lines || jsonb_build_array(jsonb_build_object('id', v_prod.id, 'name', v_prod.name, 'image', v_prod.image, 'price', v_prod.price, 'qty', r.qty));
  end loop;

  select value into v_settings from public.cms_documents where key = 'settings';
  v_thresh := coalesce((v_settings ->> 'freeShippingThreshold')::numeric, 60);
  v_flat := coalesce((v_settings ->> 'shippingFlat')::numeric, 6);
  v_ship := case when v_sub >= v_thresh then 0 else v_flat end;

  v_addr := jsonb_build_object('name', trim(p_customer ->> 'name'), 'email', v_email, 'address', trim(p_customer ->> 'address'),
    'city', trim(p_customer ->> 'city'), 'zip', trim(p_customer ->> 'zip'), 'country', trim(p_customer ->> 'country'));

  insert into public.orders (id, user_id, email, customer, shipping_address, items, item_count, subtotal, shipping, total)
  values ('AU-' || upper(substr(md5(random()::text || clock_timestamp()::text), 1, 8)), auth.uid(), v_email, v_addr, v_addr, v_lines, v_count, v_sub, v_ship, v_sub + v_ship)
  returning * into v_order;
  return to_jsonb(v_order);
end;
$$;

-- Order confirmation page: the unguessable order id acts as the key, so guests can see their receipt.
create or replace function public.get_order(p_id text) returns jsonb
language plpgsql stable security definer set search_path = public as $$
declare v_order public.orders%rowtype;
begin
  select * into v_order from public.orders where id = p_id;
  if not found then raise exception 'Order not found'; end if;
  return to_jsonb(v_order);
end;
$$;

create or replace function public.subscribe(p_email text) returns void
language plpgsql security definer set search_path = public as $$
begin
  if lower(trim(p_email)) !~* '^[^@\s]+@[^@\s]+\.[^@\s]+$' then raise exception 'Enter a valid email address'; end if;
  insert into public.subscribers (email) values (lower(trim(p_email))) on conflict (email) do nothing;
end;
$$;

grant execute on function public.place_order(jsonb, jsonb), public.get_order(text), public.subscribe(text), public.is_admin() to anon, authenticated;

-- ---------- Image storage ---------------------------------------------------------------
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('images', 'images', true, 5242880, array['image/jpeg', 'image/png', 'image/webp', 'image/gif'])
on conflict (id) do update set public = true, file_size_limit = 5242880, allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "images public read" on storage.objects;
create policy "images public read" on storage.objects for select using (bucket_id = 'images');
drop policy if exists "images admin insert" on storage.objects;
create policy "images admin insert" on storage.objects for insert with check (bucket_id = 'images' and public.is_admin());
drop policy if exists "images admin update" on storage.objects;
create policy "images admin update" on storage.objects for update using (bucket_id = 'images' and public.is_admin());
drop policy if exists "images admin delete" on storage.objects;
create policy "images admin delete" on storage.objects for delete using (bucket_id = 'images' and public.is_admin());

-- ---------- API access ----------------------------------------------------------------
-- Newer Supabase projects do not expose tables to the API automatically. Row-level security above
-- is what actually restricts access; these grants only let requests reach it.
grant usage on schema public to anon, authenticated;
grant select, insert, update, delete on all tables in schema public to anon, authenticated;
grant usage, select on all sequences in schema public to anon, authenticated;
