-- =====================================================================================
-- Benlle storefront + admin: database schema, security rules, functions and storage.
-- Run the generated setup.sql (this file + seed data) once in: Supabase → SQL Editor.
-- It is safe to re-run.
-- =====================================================================================

-- ---------- Admin identity ----------------------------------------------------------
-- The owner is whoever holds a CONFIRMED Supabase Auth account with the email below.
create table if not exists public.admins (
  user_id uuid primary key references auth.users (id) on delete cascade,
  created_at timestamptz not null default now()
);

create or replace function public.is_admin() returns boolean
language sql stable security definer set search_path = public as $$
  select exists (
    select 1 from public.admins a
    join auth.users u on u.id = a.user_id
    where a.user_id = auth.uid() and u.email_confirmed_at is not null
  );
$$;

create or replace function public.handle_new_user() returns trigger
language plpgsql security definer set search_path = public as $$
begin
  if lower(new.email) = 'betsykitur@gmail.com' then
    insert into public.admins (user_id) values (new.id) on conflict do nothing;
  end if;
  return new;
end;
$$;
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute function public.handle_new_user();
-- If the owner account already exists, claim it now.
insert into public.admins (user_id) select id from auth.users where lower(email) = 'betsykitur@gmail.com' on conflict do nothing;

alter table public.admins enable row level security;
drop policy if exists "admins read own" on public.admins;
create policy "admins read own" on public.admins for select using (user_id = auth.uid());

-- ---------- Catalogue ---------------------------------------------------------------
create table if not exists public.categories (
  id text primary key,
  label text not null check (char_length(label) between 1 and 80),
  position int not null default 0
);

create table if not exists public.products (
  id text primary key,
  position bigint generated by default as identity,
  slug text not null unique,
  name text not null check (char_length(name) between 1 and 160),
  subtitle text not null default '',
  category text not null default '',
  price numeric(10,2) not null check (price >= 0),
  badge text not null default '',
  rating numeric(2,1) not null default 0 check (rating between 0 and 5),
  reviews int not null default 0 check (reviews >= 0),
  stock int not null default 0 check (stock >= 0),
  image text not null default '',
  gallery jsonb not null default '[]'::jsonb,
  status text not null default 'active' check (status in ('active', 'draft')),
  featured boolean not null default false,
  description text not null default '',
  ingredients jsonb not null default '[]'::jsonb,
  size text not null default '',
  created_at timestamptz not null default now()
);
create index if not exists products_category_idx on public.products (category);

-- ---------- Website content (homepage sections, hero, collections, settings …) ----------
-- One JSON document per key. Keys: sections, hero, manifesto, collections, menu, about, routine,
-- trust, testimonials, settings. Image URLs live inside these documents and in products/journal.
create table if not exists public.cms_documents (
  key text primary key,
  value jsonb not null,
  updated_at timestamptz not null default now()
);

create table if not exists public.journal_posts (
  id text primary key,
  slug text not null unique,
  title text not null,
  excerpt text not null default '',
  category text not null default 'Journal',
  image text not null default '',
  date date not null default current_date,
  read_time int not null default 1,
  published boolean not null default true,
  body jsonb not null default '[]'::jsonb
);

-- Every image the site uses or the owner uploads (files live in the "images" storage bucket).
create table if not exists public.media_assets (
  id uuid primary key default gen_random_uuid(),
  url text not null unique,
  path text,
  created_at timestamptz not null default now()
);

-- ---------- Orders & customers ------------------------------------------------------
create table if not exists public.orders (
  id text primary key,
  user_id uuid references auth.users (id) on delete set null default auth.uid(),
  email text not null,
  customer jsonb not null default '{}'::jsonb,
  shipping_address jsonb not null default '{}'::jsonb,
  status text not null default 'pending' check (status in ('pending', 'processing', 'shipped', 'delivered', 'cancelled')),
  items jsonb not null default '[]'::jsonb,
  item_count int not null default 0,
  subtotal numeric(10,2) not null,
  shipping numeric(10,2) not null default 0,
  total numeric(10,2) not null,
  date timestamptz not null default now()
);
create index if not exists orders_user_idx on public.orders (user_id);
create index if not exists orders_email_idx on public.orders (email);

create table if not exists public.addresses (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  label text not null,
  name text not null,
  address text not null,
  city text not null,
  zip text not null,
  country text not null,
  is_default boolean not null default false,
  created_at timestamptz not null default now()
);
create unique index if not exists addresses_one_default on public.addresses (user_id) where is_default;

create table if not exists public.messages (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  email text not null,
  subject text not null default '',
  message text not null,
  read boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.subscribers (
  email text primary key,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

-- ---------- Money: where the owner receives payouts (admin only) ----------------------
-- Store identifiers only (till numbers, account names). Never put API secrets in this table.
create table if not exists public.payout_methods (
  id uuid primary key default gen_random_uuid(),
  type text not null check (type in ('mpesa', 'bank', 'paypal', 'card', 'other')),
  label text not null,
  details jsonb not null default '{}'::jsonb,
  enabled boolean not null default true,
  is_default boolean not null default false,
  created_at timestamptz not null default now()
);
create unique index if not exists payout_one_default on public.payout_methods ((true)) where is_default;

-- ---------- Shopper interest: what visitors added to carts / wishlists -------------------
create table if not exists public.shopper_activity (
  id bigint generated always as identity primary key,
  session_id text not null check (char_length(session_id) <= 64),
  user_id uuid,
  user_email text,
  kind text not null check (kind in ('add_to_cart', 'wishlist_add', 'wishlist_remove')),
  product_id text not null,
  qty int not null default 1 check (qty between 1 and 99),
  created_at timestamptz not null default now()
);
create index if not exists shopper_activity_product_idx on public.shopper_activity (product_id);
create index if not exists shopper_activity_created_idx on public.shopper_activity (created_at desc);

-- The server fills in who the shopper is, so it cannot be spoofed from the browser.
create or replace function public.stamp_activity() returns trigger
language plpgsql security definer set search_path = public as $$
begin
  new.user_id := auth.uid();
  new.user_email := (select email from auth.users where id = auth.uid());
  return new;
end;
$$;
drop trigger if exists stamp_activity on public.shopper_activity;
create trigger stamp_activity before insert on public.shopper_activity for each row execute function public.stamp_activity();

-- ---------- Row-level security ----------------------------------------------------------
alter table public.categories enable row level security;
alter table public.products enable row level security;
alter table public.cms_documents enable row level security;
alter table public.journal_posts enable row level security;
alter table public.media_assets enable row level security;
alter table public.orders enable row level security;
alter table public.addresses enable row level security;
alter table public.messages enable row level security;
alter table public.subscribers enable row level security;
alter table public.payout_methods enable row level security;
alter table public.shopper_activity enable row level security;

do $$
declare t text;
begin
  -- Public read, admin write
  foreach t in array array['categories', 'cms_documents', 'media_assets'] loop
    execute format('drop policy if exists "%1$s public read" on public.%1$s', t);
    execute format('create policy "%1$s public read" on public.%1$s for select using (true)', t);
    execute format('drop policy if exists "%1$s admin write" on public.%1$s', t);
    execute format('create policy "%1$s admin write" on public.%1$s for all using (public.is_admin()) with check (public.is_admin())', t);
  end loop;
  -- Admin only
  foreach t in array array['subscribers', 'payout_methods'] loop
    execute format('drop policy if exists "%1$s admin only" on public.%1$s', t);
    execute format('create policy "%1$s admin only" on public.%1$s for all using (public.is_admin()) with check (public.is_admin())', t);
  end loop;
end $$;

drop policy if exists "products read" on public.products;
create policy "products read" on public.products for select using (status = 'active' or public.is_admin());
drop policy if exists "products admin write" on public.products;
create policy "products admin write" on public.products for all using (public.is_admin()) with check (public.is_admin());

drop policy if exists "journal read" on public.journal_posts;
create policy "journal read" on public.journal_posts for select using (published or public.is_admin());
drop policy if exists "journal admin write" on public.journal_posts;
create policy "journal admin write" on public.journal_posts for all using (public.is_admin()) with check (public.is_admin());

-- Orders are created only through place_order(); customers read their own, the owner reads all.
drop policy if exists "orders read" on public.orders;
create policy "orders read" on public.orders for select using (user_id = auth.uid() or public.is_admin());
drop policy if exists "orders admin update" on public.orders;
create policy "orders admin update" on public.orders for update using (public.is_admin()) with check (public.is_admin());

drop policy if exists "addresses owner" on public.addresses;
create policy "addresses owner" on public.addresses for all using (user_id = auth.uid()) with check (user_id = auth.uid());

drop policy if exists "messages insert" on public.messages;
create policy "messages insert" on public.messages for insert with check (
  read = false and char_length(name) between 1 and 200 and char_length(subject) <= 300
  and char_length(message) between 5 and 5000 and email ~* '^[^@\s]+@[^@\s]+\.[^@\s]+$'
);
drop policy if exists "messages admin" on public.messages;
create policy "messages admin" on public.messages for select using (public.is_admin());
drop policy if exists "messages admin update" on public.messages;
create policy "messages admin update" on public.messages for update using (public.is_admin()) with check (public.is_admin());
drop policy if exists "messages admin delete" on public.messages;
create policy "messages admin delete" on public.messages for delete using (public.is_admin());

drop policy if exists "activity insert" on public.shopper_activity;
create policy "activity insert" on public.shopper_activity for insert with check (true);
drop policy if exists "activity admin read" on public.shopper_activity;
create policy "activity admin read" on public.shopper_activity for select using (public.is_admin());
drop policy if exists "activity admin delete" on public.shopper_activity;
create policy "activity admin delete" on public.shopper_activity for delete using (public.is_admin());

-- ---------- Functions the storefront calls ------------------------------------------------
-- Checkout. Prices, stock and shipping are decided HERE, never trusted from the browser.
create or replace function public.place_order(p_customer jsonb, p_items jsonb) returns jsonb
language plpgsql security definer set search_path = public as $$
declare
  k text; r record; v_prod public.products%rowtype; v_lines jsonb := '[]'::jsonb;
  v_sub numeric := 0; v_count int := 0; v_ship numeric; v_settings jsonb; v_thresh numeric; v_flat numeric;
  v_addr jsonb; v_email text; v_order public.orders%rowtype;
begin
  if p_customer is null or jsonb_typeof(p_customer) <> 'object' then raise exception 'Missing customer details'; end if;
  foreach k in array array['name', 'email', 'address', 'city', 'zip', 'country'] loop
    if coalesce(trim(p_customer ->> k), '') = '' then raise exception 'Please fill in your %', k; end if;
    if char_length(p_customer ->> k) > 300 then raise exception 'Your % is too long', k; end if;
  end loop;
  v_email := lower(trim(p_customer ->> 'email'));
  if v_email !~* '^[^@\s]+@[^@\s]+\.[^@\s]+$' then raise exception 'Enter a valid email address'; end if;
  if p_items is null or jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items) not between 1 and 50 then
    raise exception 'Your bag is empty';
  end if;
  for r in select e from jsonb_array_elements(p_items) e loop
    if coalesce(r.e ->> 'id', '') = '' or coalesce(r.e ->> 'qty', '') !~ '^[0-9]{1,2}$' or (r.e ->> 'qty')::int < 1 then
      raise exception 'Your bag has an invalid item';
    end if;
  end loop;

  for r in select e ->> 'id' as id, sum((e ->> 'qty')::int)::int as qty
           from jsonb_array_elements(p_items) e group by e ->> 'id' order by e ->> 'id' loop
    select * into v_prod from public.products where id = r.id and status = 'active' for update;
    if not found then raise exception 'An item in your bag is no longer available'; end if;
    if v_prod.stock < r.qty then
      raise exception 'Only % left of %', v_prod.stock, v_prod.name;
    end if;
    update public.products set stock = stock - r.qty where id = v_prod.id;
    v_sub := v_sub + v_prod.price * r.qty;
    v_count := v_count + r.qty;
    v_lines := v_lines || jsonb_build_array(jsonb_build_object('id', v_prod.id, 'name', v_prod.name, 'image', v_prod.image, 'price', v_prod.price, 'qty', r.qty));
  end loop;

  select value into v_settings from public.cms_documents where key = 'settings';
  v_thresh := coalesce((v_settings ->> 'freeShippingThreshold')::numeric, 60);
  v_flat := coalesce((v_settings ->> 'shippingFlat')::numeric, 6);
  v_ship := case when v_sub >= v_thresh then 0 else v_flat end;

  v_addr := jsonb_build_object('name', trim(p_customer ->> 'name'), 'email', v_email, 'address', trim(p_customer ->> 'address'),
    'city', trim(p_customer ->> 'city'), 'zip', trim(p_customer ->> 'zip'), 'country', trim(p_customer ->> 'country'));

  insert into public.orders (id, user_id, email, customer, shipping_address, items, item_count, subtotal, shipping, total)
  values ('AU-' || upper(substr(md5(random()::text || clock_timestamp()::text), 1, 8)), auth.uid(), v_email, v_addr, v_addr, v_lines, v_count, v_sub, v_ship, v_sub + v_ship)
  returning * into v_order;
  return to_jsonb(v_order);
end;
$$;

-- Order confirmation page: the unguessable order id acts as the key, so guests can see their receipt.
create or replace function public.get_order(p_id text) returns jsonb
language plpgsql stable security definer set search_path = public as $$
declare v_order public.orders%rowtype;
begin
  select * into v_order from public.orders where id = p_id;
  if not found then raise exception 'Order not found'; end if;
  return to_jsonb(v_order);
end;
$$;

create or replace function public.subscribe(p_email text) returns void
language plpgsql security definer set search_path = public as $$
begin
  if lower(trim(p_email)) !~* '^[^@\s]+@[^@\s]+\.[^@\s]+$' then raise exception 'Enter a valid email address'; end if;
  insert into public.subscribers (email) values (lower(trim(p_email))) on conflict (email) do nothing;
end;
$$;

grant execute on function public.place_order(jsonb, jsonb), public.get_order(text), public.subscribe(text), public.is_admin() to anon, authenticated;

-- ---------- Image storage ---------------------------------------------------------------
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('images', 'images', true, 5242880, array['image/jpeg', 'image/png', 'image/webp', 'image/gif'])
on conflict (id) do update set public = true, file_size_limit = 5242880, allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "images public read" on storage.objects;
create policy "images public read" on storage.objects for select using (bucket_id = 'images');
drop policy if exists "images admin insert" on storage.objects;
create policy "images admin insert" on storage.objects for insert with check (bucket_id = 'images' and public.is_admin());
drop policy if exists "images admin update" on storage.objects;
create policy "images admin update" on storage.objects for update using (bucket_id = 'images' and public.is_admin());
drop policy if exists "images admin delete" on storage.objects;
create policy "images admin delete" on storage.objects for delete using (bucket_id = 'images' and public.is_admin());

-- ---------- API access ----------------------------------------------------------------
-- Newer Supabase projects do not expose tables to the API automatically. Row-level security above
-- is what actually restricts access; these grants only let requests reach it.
grant usage on schema public to anon, authenticated;
grant select, insert, update, delete on all tables in schema public to anon, authenticated;
grant usage, select on all sequences in schema public to anon, authenticated;

-- Seed data generated from src/data/*. Safe to re-run: existing rows are left untouched.

insert into public.categories (id, label, position) values
  ('cleansers', 'Cleansers', 0),
  ('serums', 'Serums', 1),
  ('moisturizers', 'Moisturizers', 2),
  ('oils', 'Oils', 3)
on conflict (id) do nothing;

insert into public.products (id, slug, name, subtitle, category, price, badge, rating, reviews, stock, image, gallery, status, featured, description, ingredients, size) values
  ('p1', 'barrier-repair-serum', 'Barrier Repair Serum', 'Ceramides + Niacinamide 5%', 'serums', 42, 'New', 4.5, 162, 48, '/images/serum.jpg', '["/images/serum.jpg","/images/lifestyle-1.jpg","/images/lifestyle-2.jpg"]'::jsonb, 'active', true, 'A lightweight serum that restores the skin barrier with ceramides and 5% niacinamide. Calms redness and visibly improves texture in two weeks.', '["Ceramide NP","Niacinamide 5%","Panthenol","Squalane"]'::jsonb, '30 ml'),
  ('p2', 'cloud-cleanser', 'Cloud Cleanser', 'Amino Acid Gel', 'cleansers', 22, 'pH 5.5', 4.8, 311, 120, '/images/cleanser.jpg', '["/images/cleanser.jpg","/images/cleanse.jpg","/images/lifestyle-2.jpg"]'::jsonb, 'active', true, 'A pH-balanced gel cleanser that lifts impurities without stripping. Leaves skin soft, never tight.', '["Coco-glucoside","Glycerin","Aloe vera","Green tea"]'::jsonb, '150 ml'),
  ('p3', 'dew-moisture-cream', 'Dew Moisture Cream', 'Ceramide-rich hydration', 'moisturizers', 38, '', 4.6, 204, 64, '/images/cream.jpg', '["/images/cream.jpg","/images/nourish.jpg","/images/lifestyle-2.jpg"]'::jsonb, 'active', false, 'A cushiony daily moisturizer with ceramides and hyaluronic acid for all-day barrier-supporting hydration.', '["Ceramide AP","Hyaluronic acid","Shea butter","Oat extract"]'::jsonb, '50 ml'),
  ('p4', 'radiance-treatment-serum', 'Radiance Treatment Serum', 'Vitamin C + Botanical Blend', 'serums', 54, 'Bestseller', 4.7, 428, 9, '/images/radiance.jpg', '["/images/radiance.jpg","/images/lifestyle-2.jpg","/images/lifestyle-2.jpg"]'::jsonb, 'active', true, 'A stabilised vitamin C serum with botanical extracts to brighten dullness and even tone.', '["Ascorbyl glucoside","Rosehip","Ferulic acid","Licorice root"]'::jsonb, '30 ml'),
  ('p5', 'hydra-restore-essence', 'Hydra Restore Essence', 'Hyaluronic acid + Aloe', 'serums', 29, '', 4.4, 97, 80, '/images/essence.jpg', '["/images/essence.jpg","/images/hydrate.jpg","/images/lifestyle-2.jpg"]'::jsonb, 'active', false, 'A weightless essence that floods skin with multi-weight hyaluronic acid.', '["Hyaluronic acid","Aloe vera","Betaine","Cucumber extract"]'::jsonb, '100 ml'),
  ('p6', 'botanical-face-oil', 'Botanical Face Oil', 'Jojoba + Rosehip + Bakuchiol', 'oils', 46, 'New', 4.9, 76, 0, '/images/oil.jpg', '["/images/oil.jpg","/images/lifestyle-1.jpg","/images/lifestyle-2.jpg"]'::jsonb, 'active', false, 'A silky blend of cold-pressed oils with bakuchiol, a gentle plant alternative to retinol.', '["Jojoba oil","Rosehip oil","Bakuchiol","Vitamin E"]'::jsonb, '30 ml'),
  ('p7', 'renewal-night-cream', 'Renewal Night Cream', 'Peptides + Botanical support', 'moisturizers', 58, '', 4.5, 133, 31, '/images/night.jpg', '["/images/night.jpg","/images/nourish.jpg","/images/lifestyle-2.jpg"]'::jsonb, 'draft', false, 'An overnight cream with peptides that supports skin renewal while you sleep.', '["Peptide complex","Squalane","Chamomile","Shea butter"]'::jsonb, '50 ml')
on conflict (id) do nothing;

insert into public.cms_documents (key, value) values
  ('sections', '[{"id":"hero","label":"Hero banner","visible":true},{"id":"manifesto","label":"Statement strip","visible":true},{"id":"collections","label":"Collections","visible":true},{"id":"featured","label":"Featured products","visible":true},{"id":"about","label":"About / our story","visible":true},{"id":"routine","label":"Routine steps","visible":true},{"id":"trust","label":"Trust highlights","visible":true},{"id":"testimonials","label":"Testimonials","visible":true},{"id":"journal","label":"Journal preview","visible":true},{"id":"contact","label":"Contact form","visible":true}]'::jsonb),
  ('hero', '{"eyebrow":"","primaryLabel":"Shop Now","primaryLink":"/shop","secondaryLabel":"Learn More","secondaryLink":"/#about","image":"https://images.unsplash.com/photo-1543366749-4dad497ea0a0?w=1471&q=80","alt":"Skincare model with dewy skin","title":"Natural Skincare","text":"Awaken your skin with gentle actives and nourishing oils. Formulated to restore barrier health and glow naturally."}'::jsonb),
  ('manifesto', '{"lines":["Refresh your skin,","love yourself,","renew your glow."],"images":["/images/model-serum.jpg","/images/model-mask.jpg","/images/leaf.jpg"]}'::jsonb),
  ('collections', '[{"id":"hydrate","title":"Hydrate & Restore","blurb":"Moisture-rich serums with hyaluronic acid","series":"Essential Hydration Collection","image":"/images/hydrate.jpg","category":"serums"},{"id":"cleanse","title":"Cleanse & Purify","blurb":"pH-balanced cleansers for sensitive skin","series":"Gentle Care Collection","image":"/images/cleanse.jpg","category":"cleansers"},{"id":"renew","title":"Renew & Repair","blurb":"Anti-aging actives with botanical support","series":"Advanced Renewal Series","image":"/images/renew.jpg","category":"serums"},{"id":"botanical","title":"Botanical Blend","blurb":"Nature-inspired actives for healthy glow","series":"Natural Radiance Collection","image":"/images/botanical.jpg","category":"oils"},{"id":"nourish","title":"Nourish & Protect","blurb":"Rich moisturizers with barrier protection","series":"Barrier Repair Collection","image":"/images/nourish.jpg","category":"moisturizers"}]'::jsonb),
  ('menu', '[{"id":"cleansers","title":"Refresh: Cleansers","blurb":"pH-balanced, non‑stripping","image":"/images/cleanser.jpg","category":"cleansers"},{"id":"serums","title":"Treat: Serums","blurb":"Actives that respect your barrier","image":"/images/serum.jpg","category":"serums"},{"id":"moisturizers","title":"Nourish: Moisturizers","blurb":"Ceramide-rich hydration","image":"/images/cream.jpg","category":"moisturizers"}]'::jsonb),
  ('about', '{"eyebrow":"Our story","title":"Skincare that respects your skin","text":["Benlle began with a simple question: why do effective formulas have to be harsh? We pair clinically proven botanicals with barrier-friendly actives, so skin gets stronger, calmer and clearer.","Every formula is dermatologist tested, vegan, and packaged in recyclable glass."],"image":"/images/about.jpg","stats":[{"value":"98%","label":"felt calmer skin in 2 weeks*"},{"value":"12","label":"clinical studies"},{"value":"100%","label":"recyclable packaging"}],"note":"*Consumer study, 112 participants, 14 days."}'::jsonb),
  ('routine', '{"eyebrow":"The routine","title":"Three steps. Nothing more.","text":"A good routine is one you will actually do. Skin renews roughly every 28 days, so give it a month.","steps":[{"title":"Cleanse","text":"Lukewarm water and a gentle, pH-balanced gel. Skin should feel soft, never squeaky.","category":"cleansers","cta":"Shop cleansers"},{"title":"Treat","text":"A serum matched to your main concern, whether that is barrier, hydration or glow.","category":"serums","cta":"Shop serums"},{"title":"Nourish","text":"Finish with a rich moisturizer to seal everything in, and sunscreen by day.","category":"moisturizers","cta":"Shop moisturizers"}]}'::jsonb),
  ('navigation', '[{"label":"Shop","to":"/shop","dropdown":false},{"label":"About","to":"/#about","dropdown":false},{"label":"Contact","to":"/#contact","dropdown":false},{"label":"Collections","to":"/#collections","dropdown":true},{"label":"Journal","to":"/journal","dropdown":false}]'::jsonb),
  ('copy', '{"collectionsTitle":"Explore collections","collectionsText":"Targeted routines for every skin goal.","featuredTitle":"Featured products","featuredText":"Thoughtful formulas, consciously packaged.","journalTitle":"From the journal","contactTitle":"Get in touch","contactText":"Questions about a product or your routine? Our skin advisors reply within a day.","newsletterTitle":"Stay in the glow","newsletterText":"Routines, launches and 10% off your first order."}'::jsonb),
  ('brand', '{"accent":"#10b981"}'::jsonb),
  ('trust', '[{"icon":"Leaf","title":"Clinically proven botanicals","text":"Every active is backed by independent clinical data."},{"icon":"Recycle","title":"Sustainably packaged","text":"Recyclable glass and refillable pumps."},{"icon":"ShieldCheck","title":"Dermatologist tested","text":"Gentle on even the most sensitive skin."},{"icon":"Truck","title":"Free shipping over $60","text":"Carbon-neutral delivery worldwide."}]'::jsonb),
  ('testimonials', '[{"id":"t1","name":"Amara O.","text":"My skin has never felt calmer. The barrier serum is a staple.","rating":5},{"id":"t2","name":"Lena K.","text":"Cloud Cleanser is the first cleanser that does not leave me tight.","rating":5},{"id":"t3","name":"Mateo R.","text":"Simple, effective, and the packaging is gorgeous.","rating":4}]'::jsonb),
  ('settings', '{"name":"Benlle","tagline":"Botanical · Clinical · Kind","description":"Natural skincare crafted with clinically proven botanicals. Gentle, effective, and sustainable.","announcements":["Free shipping on orders over $60","New: Barrier Repair Serum 2.0 is here"],"freeShippingThreshold":60,"shippingFlat":6,"contact":{"email":"hello@benlle.example","phone":"+1 (555) 010-2030"}}'::jsonb)
on conflict (key) do nothing;

insert into public.journal_posts (id, slug, title, excerpt, category, image, date, read_time, published, body) values
  ('j1', 'rebuild-a-stressed-skin-barrier', 'How to rebuild a stressed skin barrier', 'Redness, tightness and stinging are often barrier signals, not skin types.', 'Skin science', '/images/journal-barrier.jpg', '2026-09-12', 6, true, '["Your skin barrier is a thin layer of lipids and cells that keeps moisture in and irritants out. When it is compromised, skin feels tight, looks red and reacts to products it used to tolerate.","Start by simplifying. Pause exfoliating acids and strong actives for two weeks, and use a pH-balanced cleanser that does not leave skin squeaky.","Then rebuild. Ceramides, cholesterol and fatty acids replace what is missing, while niacinamide supports the skin''s own lipid production. Layer a serum under a rich moisturizer morning and night.","Most people see calmer, more comfortable skin in about two weeks. Reintroduce actives one at a time, slowly."]'::jsonb),
  ('j2', 'niacinamide-explained', 'Niacinamide, explained simply', 'One of the most studied ingredients in skincare, and what it actually does.', 'Ingredients', '/images/journal-niacinamide.jpg', '2026-08-28', 4, true, '["Niacinamide is a form of vitamin B3. It is well tolerated, works for nearly every skin type and has clinical data behind it.","At around 5% it helps regulate oil, soften the look of pores, calm redness and support the skin barrier.","It pairs well with almost everything, including vitamin C, ceramides and hyaluronic acid. Use it once or twice daily after cleansing."]'::jsonb),
  ('j3', 'slower-morning-routine', 'A slower morning routine in three steps', 'Cleanse, treat, protect. Nothing more is needed.', 'Routine', '/images/journal-routine.jpg', '2026-08-05', 5, true, '["A good routine is one you will actually do. Three steps are enough: cleanse, treat, nourish.","Cleanse with lukewarm water and a gentle gel. Treat with a serum matched to your main concern. Finish with a moisturizer and sunscreen.","Give it a month before judging results. Skin renews roughly every 28 days, so patience is part of the routine."]'::jsonb)
on conflict (id) do nothing;

insert into public.media_assets (url) values
  ('https://images.unsplash.com/photo-1543366749-4dad497ea0a0?w=1471&q=80'),
  ('/images/serum.jpg'),
  ('/images/cleanser.jpg'),
  ('/images/cream.jpg'),
  ('/images/radiance.jpg'),
  ('/images/essence.jpg'),
  ('/images/oil.jpg'),
  ('/images/night.jpg'),
  ('/images/hydrate.jpg'),
  ('/images/cleanse.jpg'),
  ('/images/renew.jpg'),
  ('/images/botanical.jpg'),
  ('/images/nourish.jpg'),
  ('/images/model-serum.jpg'),
  ('/images/model-mask.jpg'),
  ('/images/leaf.jpg'),
  ('/images/journal-barrier.jpg'),
  ('/images/journal-niacinamide.jpg'),
  ('/images/journal-routine.jpg'),
  ('/images/lifestyle-1.jpg'),
  ('/images/lifestyle-2.jpg'),
  ('/images/about.jpg')
on conflict (url) do nothing;
